### ISSUE TITLE
Problems with Range Options

### ISSUE THREAD

**Issue by ubergeek77** [BrianEstrada/PokeScanner#85]
The 3 settings under Range Options tend to be a bit buggy for me after the update. To keep it brief, all 3 options tend to not get updated properly. For example, if I change the Search Radius to 2, sometimes that setting will not change, and when I re-enter the settings, I will see that it is still set to 4, which is the default setting. The "Show Range Preview" and "Show Range" toggles have similar behavior. I can toggle them on and off, but I'll have to do this a few times to get the setting to stick, even if I wait for the map to update first.

Also, the Pokemon Filters don't seem to be working at all for me. It's probably due to the same reason, which is that settings aren't saving.

I've not yet had any problem with the icon scale setting or gym filters.

**Comment by rhari991** [comment]
The filters issue was just fixed recently, please try the newest apk file

**Comment by ubergeek77** [comment]
Ah, I totally overlooked that commit. Thanks, I'll clone and build and see if I'm still having these problems.

**Comment by BrianEstrada** [comment]
I'm testing on 3 devices and everything seems to save fine?

**Comment by BrianEstrada** [comment]
What device and version are you on?

**Comment by ubergeek77** [comment]
Actually, it looks like the Search Radius keeps getting reset every time you toggle "Show Range" and "Show Range Preview." I didn't realize this when I was trying to wrap my head around the issue, but I'm doing it right now and can reproduce it very easily. I have an LGV10 on Android 6.0.

**Comment by BrianEstrada** [comment]
@ubergeek77 That's good work I'll see whats causing that issue it shouldn't be too hard to track down with that information :)

**Comment by BrianEstrada** [comment]
Fixed in 1.6.2!
